before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: hrv-darwin
  binary: hrv
  main: ./cmd/hrv/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/harvest.version={{.Version}} -X github.com/k1LoW/harvest.commit={{.FullCommit}} -X github.com/k1LoW/harvest.date={{.Date}} -X github.com/k1LoW/harvest/version.Version={{.Version}}
  env:
    - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
-
  id: hrv-linux
  binary: hrv
  main: ./cmd/hrv/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/harvest.version={{.Version}} -X github.com/k1LoW/harvest.commit={{.FullCommit}} -X github.com/k1LoW/harvest.date={{.Date}} -X github.com/k1LoW/harvest/version.Version={{.Version}}
    - -linkmode external
    - -extldflags "-static"
  env:
    - CGO_ENABLED=1
    - CC=/usr/local/bin/x86_64-linux-musl-cc
  goos:
    - linux
  goarch:
    - amd64
archives:
-
  id: harvest-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
-
  name: harvest
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/harvest
  description: Portable log aggregation tool for middle-scale system operation/observation.
  install: |
    system './hrv', 'completion', 'bash', '--out', 'hrv.bash'
    system './hrv', 'completion', 'zsh', '--out', 'hrv.zsh'
    bin.install 'hrv'
    bash_completion.install 'hrv.bash' => 'hrv'
    zsh_completion.install 'hrv.zsh' => '_hrv'
nfpms:
  -
    id: harvest-nfpms
    name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - hrv-linux
    homepage: https://github.com/k1LoW/harvest
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: Portable log aggregation tool for middle-scale system operation/observation.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
